### ISSUE TITLE
Question about the evaluation metric

### ISSUE THREAD

**Issue by dlsrbgg33** [renwang435/video-ttt-release#2]
Hi,

Thank you for your great work and contribution to the video recognition community.

I am wondering if you have evaluated your method and baselines using any video metrics (e.g., VPQ or STQ)?

Thank you.

**Comment by renwang435** [comment]
Hi, we haven't evaluated on video metrics; the idea behind our work is to adapt the model to every incoming frame. That is, we treat every incident frame as a single test instance (and so, for example, there are no guarantees about instance identity from frame-to-frame, making it difficult to compute things like VPQ/STQ etc.)
