### ISSUE TITLE
Need Help with TENT Code

### ISSUE THREAD

**Issue by zwbx** [renwang435/video-ttt-release#3]
Hey there,

I'm really interested in this project!  I notice the comparison of other methods, e.g. TENT, but I can't find it in the project. Could you point me in the right direction or share the code with me? Excited to learn more and get involved!

**Comment by renwang435** [comment]
Hi, the TENT loss can be found here: https://github.com/DequanWang/tent/blob/master/tent.py#L45

It only requires you overload the loss function, similar to what is done here: https://github.com/renwang435/video-ttt-release/blob/main/mask2former/modeling/criterion.py#L251
